name: Deploy NomenV Application to Production Server

on:
  # NOT on pull requests -- it's a security risk since anyone can make a PR.
  push:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
#Add AWS Credentials to GitHub Secrets
#Add these secrets to your repo:
#AWS_ACCESS_KEY_ID
#AWS_SECRET_ACCESS_KEY
#AWS_REGION
#AWS_SECURITY_GROUP_ID


  #    # Step 1: Add 0.0.0.0/0 rule for port 9876
      #- name: Open SSH port for all IPs
        #uses: aws-actions/aws-cli@v1
        #with:
          #aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          #aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          #aws-region: ${{ secrets.AWS_REGION }}
          #args: >
            #ec2 authorize-security-group-ingress
            #--group-id ${{ secrets.AWS_SECURITY_GROUP_ID }}
            #--protocol tcp
            #--port 9876
            #--cidr 0.0.0.0/0


      # This connects from IP 135.119.237.65 (Micrsoft Azure)
      - name: Test SSH connection
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.SSH_PORT }}
          script: whoami
      
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
#          php-version: '8.3'
          php-version: '8.2.9'
          extensions: mbstring, xml, curl, zip, bcmath, gd, fileinfo, openssl, 
          coverage: none

#      - name: Install Composer dependencies
#        run: composer install --no-dev --no-progress --no-interaction --prefer-dist --optimize-autoloader

      - name: Install Node.js dependencies
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Install npm dependencies
        run: npm install

      - name: Build frontend assets
        run: npm run build

      - name: Deploy to production server
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.SSH_PORT }}
          source: "./dist"
          target: "/home/quarkphysics/nomenV"
          rm: false
          debug: true
          strip_components: 1

      # Final step: Remove 0.0.0.0/0 rule after deploy
    #  - name: Close SSH port for all IPs
    #    if: always()
    #    uses: aws-actions/aws-cli@v1
    #    with:
    #      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #      aws-region: ${{ secrets.AWS_REGION }}
    #      args: >
    #        ec2 revoke-security-group-ingress
    #        --group-id ${{ secrets.AWS_SECURITY_GROUP_ID }}
    #        --protocol tcp
    #        --port 9876
    #        --cidr 0.0.0.0/0

# or build on server (deleting much above)
        # script: |
        #    cd /path/to/laravel
        #    php artisan down
        #    git pull
        #    npm ci
        #    npm run build
        #    composer i --no-interaction -q --no-progress
        #    php artisan migrate --force
        #    php artisan optimize
        #    php artisan up

########################## END ###########################